name: recurrence
description: A custom recurrence rule implementation. It has weird serialization, but it works. Depends on moment_dart.
version: 0.0.6
repository: https://github.com/sadespresso/recurrence
homepage: https://github.com/sadespresso/recurrence
issue_tracker: https://github.com/sadespresso/moment_dart/issues
funding:
  - https://buymeacoffee.com/sadespresso

environment:
  sdk: ">=2.19.4 <4.0.0"

dependencies:
  moment_dart: ^5.0.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
